server:
  port: 80100

jwt:
  secret-key: ekh32837389owhjeg3782rdshqjvg32975d37286763ry237652ryedgf6

app:
  security:
    trust-inbound-headers: false
    public-routes:
      - "/v1/auth/**"
      - "/webhook/**"

  rate-limit:
    method: fixed
    use-case:
      api-keys:
        requests-per-minute: 200

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              uri: lb://merchant-service
              predicates:
                - Path=/v1/auth/**, /v1/merchants/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/v1/orders/**, /v1/payments/**

            - id: vault-service
              uri: lb://vault-service
              predicates:
                - Path=/v1/vault/**

            - id: operation-service
              uri: lb://operation-service
              predicates:
                - Path=/v1/operation/**
  
