server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/razorpay-merchant-db

jwt:
  secret-key: ekh32837389owhjeg3782rdshqjvg32975d37286763ry237652ryedgf6

webhook:
  secret-encryption.master-key: JwTYL/CJEjaHzfhPQoCwuFrcyNeaSt9cunCUgbMXGWI=
